document.addEventListener("DOMContentLoaded",()=>{"use strict";
const CALENDLY_URL="https://calendly.com/DITT-NAMN/DITT-MOTE"; // BYT DENNA SEN
const videos=[{src:"videos/event.mp4",poster:"images/event.jpg",category:"Event",title:"Event & aftermovies",description:"Känslan från kvällen, koncentrerad till film."},{src:"videos/lifestyle.mp4",poster:"images/lifestyle.jpg",category:"Sociala medier",title:"Innehåll som stannar kvar",description:"Korta format skapade för Reels och sociala medier."},{src:"videos/sport.mp4",poster:"images/sport.jpg",category:"Sport",title:"Sport & matchdag",description:"Rörelse, intensitet och ögonblicket mellan målen."}];
const slider=document.querySelector(".motion-slider"),center=document.querySelector(".motion-slider__center"),video=document.getElementById("motionVideo"),prev=document.getElementById("previousVideo"),next=document.getElementById("nextVideo"),title=document.getElementById("motionVideoTitle"),desc=document.getElementById("motionVideoDescription"),cat=document.getElementById("motionVideoCategory"),num=document.getElementById("motionVideoNumber"),dots=document.getElementById("motionVideoDots");let current=0,busy=false;
function renderDots(){if(!dots)return;dots.innerHTML="";videos.forEach((v,i)=>{const b=document.createElement("button");b.type="button";b.className="motion-slider__dot";b.setAttribute("aria-label",`Visa ${v.title}`);b.addEventListener("click",()=>change(i));dots.appendChild(b)})}
function updateDots(){dots?.querySelectorAll("button").forEach((d,i)=>d.classList.toggle("is-active",i===current))}
function change(index,animate=true){if(!video||busy)return;busy=true;const i=(index+videos.length)%videos.length;center?.classList.toggle("is-changing",animate);setTimeout(()=>{current=i;const v=videos[i];video.src=v.src;video.poster=v.poster;video.muted=true;video.load();video.play().catch(()=>{});cat.textContent=v.category;title.textContent=v.title;desc.textContent=v.description;num.textContent=`${String(i+1).padStart(2,"0")} / ${String(videos.length).padStart(2,"0")}`;updateDots();center?.classList.remove("is-changing");busy=false},animate?220:0)}
if(slider&&video){renderDots();change(0,false);prev?.addEventListener("click",()=>change(current-1));next?.addEventListener("click",()=>change(current+1));document.addEventListener("keydown",e=>{const r=slider.getBoundingClientRect();if(r.top<innerHeight&&r.bottom>0){if(e.key==="ArrowLeft")change(current-1);if(e.key==="ArrowRight")change(current+1)}})}
const nav=document.getElementById("nav"),burger=document.getElementById("burger"),navLinks=document.getElementById("navLinks"),progress=document.getElementById("scrollProgress"),toTop=document.getElementById("toTop");burger?.addEventListener("click",()=>{const open=navLinks.classList.toggle("open");burger.setAttribute("aria-expanded",String(open))});navLinks?.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>navLinks.classList.remove("open")));
function scrollUI(){const y=scrollY,max=document.documentElement.scrollHeight-innerHeight;progress.style.transform=`scaleX(${max?Math.min(y/max,1):0})`;nav?.classList.toggle("scrolled",y>20);toTop?.classList.toggle("visible",y>500)}addEventListener("scroll",scrollUI,{passive:true});scrollUI();toTop?.addEventListener("click",()=>scrollTo({top:0,behavior:"smooth"}));
const links=[...document.querySelectorAll('.nav__links a[href^="#"]')],sections=links.map(a=>document.querySelector(a.getAttribute("href"))).filter(Boolean);if("IntersectionObserver"in window){const ob=new IntersectionObserver(es=>{const v=es.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(v)links.forEach(a=>a.classList.toggle("active",a.getAttribute("href")===`#${v.target.id}`))},{rootMargin:"-35% 0px -55%",threshold:[.01,.2,.5]});sections.forEach(s=>ob.observe(s))}
const revealObs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("is-visible");revealObs.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll(".reveal").forEach(el=>revealObs.observe(el));
document.querySelectorAll(".js-book").forEach(btn=>btn.addEventListener("click",e=>{e.preventDefault();if(window.Calendly&&CALENDLY_URL&&!CALENDLY_URL.includes("DITT-")){Calendly.initPopupWidget({url:CALENDLY_URL})}else{window.open(CALENDLY_URL,"_blank","noopener,noreferrer")}}));
const year=document.getElementById("year");if(year)year.textContent=new Date().getFullYear();
});
